#
# Makefile for websites powered by Hugo
#
build:
	# Build the site
	hugo --minify
	# Delete the author pages generated by hugo.
	find public/author ! -path "public/author" ! -path "public/author/dongdong-tian" -exec rm -rf {} +

serve:
	hugo server --disableFastRender

clean:
	-rm -rf public resources
